services:
  mysql:
    image: mysql:8.0
    container_name: mysql_clean_arch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3307:3306"
    volumes:
      - mysql_clean_arch:/var/lib/mysql

volumes:
  mysql_clean_arch:
    driver: local