services:
  mysql:
    image: mysql:8.0
    container_name: mysql_clean_arch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3307:3306"
    volumes:
      - mysql_clean_arch:/var/lib/mysql
      - ./internal/infra/database/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_clean_arch
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    environment:
      - db_driver=mysql
      - db_host=mysql
      - db_port=3306
      - db_user=root
      - db_pass=root
      - db_name=orders
      - web_server_port=:8000
      - grpc_server_port=50051
      - graphql_server_port=8080
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_clean_arch:
    driver: local