services:
  mysql:
    image: mysql:8.0
    container_name: mysql_clean_arch
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3307:3306"
    volumes:
      - mysql_clean_arch:/var/lib/mysql
      - ./internal/infra/database/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_clean_arch:
    driver: local