POST http://localhost:8080/orders HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "id":"a",
    "price": 100.5,
    "tax": 0.5
}

### Get all orders
GET http://localhost:8080/orders

## Get order by id
GET http://localhost:8080/orders/a